// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRpolDzdjjAIC7pxRen9xwjN2YObJ_CBs',
    appId: '1:106333460791:web:47ea8faba727501ebe22b2',
    messagingSenderId: '106333460791',
    projectId: 'classtech-c37b1',
    authDomain: 'classtech-c37b1.firebaseapp.com',
    storageBucket: 'classtech-c37b1.firebasestorage.app',
    measurementId: 'G-TD6MXC6BG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0T3hKoXvry3iFz-cpNZz8rV83EG2SuV4',
    appId: '1:106333460791:android:631f36978dbc5b88be22b2',
    messagingSenderId: '106333460791',
    projectId: 'classtech-c37b1',
    storageBucket: 'classtech-c37b1.firebasestorage.app',
  );
}
